### PR TITLE
fix #3165 #3255

### LINKED ISSUE #3165: [Bug]: RPAD result bug
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e1319c52cf87b17a98008ae0dda79b72237d9ed1
- Hardware parameters:Mac M1 ARM 16GB Memory
- OS type:OSX
- Others:
```

### Actual Behavior

rpad(c, 1, *)

null

### Expected Behavior

rpad(c,'1','*')
D
D
B
C
A
B
B
E
S
B
null
*

### Steps to Reproduce

```markdown
drop table if exists t1;
create table t1 ( id int, c char(10),vc varchar(20));
insert into t1 values (1,'Daffy','Aducklife');
insert into t1 values (1,'Daffy','Aducklife');
insert into t1 values (2,'Bugs','Arabbitlife');
insert into t1 values (3,'Cowboy','Lifeontherange');
insert into t1 values (4,'Anonymous','Wannabuythisbook?');
insert into t1 values (5,'BestSeller','OneHeckuvabook');
insert into t1 values (5,'BestSeller','OneHeckuvabook');
insert into t1 values (6,'EveryoneBu','Thisverybook');
insert into t1 values (7,'SanFran','Itisasanfranlifetyle');
insert into t1 values (8,'BerkAuthor','Cool.Berkly.the.book');
insert into t1 values (9,null,null);
insert into t1 values (10,'','');
select rpad(c,'1','*') from t1;
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JackTan25**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3165 #3255

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

File: pkg/sql/plan2/function/builtin/multi/lpad.go [hunk 1]
```diff
@@ -28,6 +30,23 @@ const (
 	ParameterPadString    = int(2)
 )
 
+//for func lpad func, the second para length,it could be type.Bytes or int
```
Comment (fengttt) [inline pkg/sql/plan2/function/builtin/multi/lpad.go:33]: This does not feel right.   Please contact Peng Zhen or MingSong.    I believe you are doing the wrong way, it should go through their type conversion framework.

File: pkg/sql/plan2/function/builtin/multi/lpad.go [hunk 2]
```diff
@@ -40,8 +59,11 @@ func Lpad(vecs []*vector.Vector, proc *process.Process) (*vector.Vector, error)
 	sourceStr := vector.MustBytesCols(vecs[ParameterSourceString]) //Get the first arg
 
 	//characters length not bytes length
-	lengthsOfChars := vector.MustTCols[int64](vecs[ParameterLengths])
-
+	// lengthsOfChars := vector.MustTCols[int64](vecs[ParameterLengths])
+	lengthsOfChars, err_ := Convert(vecs[ParameterLengths].Col)
```
Comment (m-schen) [inline pkg/sql/plan2/function/builtin/multi/lpad.go:63]: you can't do type conversion here.

just put the convert logic at function register at plan2/function/builtins.go.

File: pkg/sql/plan2/function/buitins.go [hunk 3]
```diff
@@ -971,6 +971,13 @@ var builtins = map[int]Functions{
 				Args:      []types.T{types.T_varchar, types.T_int64, types.T_varchar},
 				ReturnTyp: types.T_varchar, Fn: multi.Lpad,
 			},
+			{
```
Comment (m-schen) [inline pkg/sql/plan2/function/buitins.go:974]: there is no need to register an overload
{varchar, varchar, varchar}

in fact, the implicit type convert logic for function's argument will do the work for you.
I will try to convert char or varchar to int64.

and if you don't want to use the logic, you can write a special function for the LPAD function.
just put it at Functions.TypeCheckFn

File: pkg/vectorize/rpad/rpad.go [hunk 4]
```diff
@@ -280,3 +310,30 @@ func rpadUint64(rowCount int, strs *types.Bytes, sizes []uint64, padstrs *types.
 	}
 	return results, resultNsp
 }
+
+func BytesToInt[T constraints.Signed](xs *types.Bytes, rs []T) ([]T, []bool, error) {
```
Comment (fengttt) [inline pkg/vectorize/rpad/rpad.go:314]: What does this do?  Atoi?

File: pkg/vectorize/rpad/rpad.go [hunk 5]
```diff
@@ -132,12 +150,24 @@ func rpadInt64(rowCount int, strs *types.Bytes, sizes []int64, padstrs *types.By
 	resultNsp := new(nulls.Nulls)
 	for i := 0; i < rowCount; i++ {
 		var newSize int64
+		var flag bool
 		if isConst[1] {
 			// accepts a constant literal
 			newSize = sizes[0]
+			if useFlag {
```
Comment (fengttt) [inline pkg/vectorize/rpad/rpad.go:157]: Confused -- where did flags come from?

File: pkg/sql/plan2/function/operator/cast.go [hunk 6]
```diff
@@ -755,6 +755,35 @@ func CastSameType2[T types.Date | types.Datetime | types.Timestamp](lv, rv *vect
 	return vec, nil
 }
 
+//It's an error to use CastLeftToRight when convert float to integer,So this is a special fix
+func CastFloatToInteger[T1 constraints.Float, T2 constraints.Integer](lv, rv *vector.Vector, proc *process.Process) (*vector.Vector, error) {
```
Comment (fengttt) [inline pkg/sql/plan2/function/operator/cast.go:759]: What is the error?   What is the diff between your version and the CastLeftToRight?  Can you add that in comment?

File: pkg/vectorize/rpad/rpad.go [hunk 7]
```diff
@@ -15,19 +15,32 @@
...
+	flags                []bool
+	useFlag              bool
 )
 
 const UINT16_MAX = ^uint16(0)
 
 func init() {
 	Rpad = rpad
+	StringError = errors.New("string overflow")
+	MaxSpacePerRowOfRpad = "16777216"
```
Comment (fengttt) [inline pkg/vectorize/rpad/rpad.go:43]: This Max... is a string?  That is very strange.

**Review by fengttt — COMMENTED** [review]
I think PengZheng/MingSong need to do another round of view.

**Review by JinHai-CN — CHANGES_REQUESTED** [review]
Binary file: __debug_bin should be removed from the commit.

File: pkg/vectorize/rpad/rpad.go (hunk 5 above)
Comment (JackTan25) [reply pkg/vectorize/rpad/rpad.go:157]: It's used for the non-character string "", I need this to set the result as "",but not NULL. See this: rpad("hello","",1),the result is "", and if this rpad("hello",-18446744073709551615,1),it's NULL, but the second parameter will be string. So I need to add this to fix it.

File: pkg/sql/plan2/function/operator/cast.go (hunk 6 above)
Comment (JackTan25) [reply pkg/sql/plan2/function/operator/cast.go:759]: I'll give the comments in the codes, the error is that: int the old code, if you go through the CastLeftToRight , like 1.5 will be 1, and it should be 2, but if I modify the CastLeftToRight straight, it will cause other things ,So as to avoid that, I give another func CastFloatToInteger

File: pkg/vectorize/rpad/rpad.go (hunk 4 above)
Comment (JackTan25) [reply pkg/vectorize/rpad/rpad.go:314]: Yeah, like this, the typecast.BytesToInt doesn't satisfy my need. I need more info like flags and so on to solve the problem of
typeBytes of rpad. I don't modify the typecast.BytesToInt, because the modified func is used in many places. I'm afraid it cause many other errors.

File: test/cases/function/func_math_round.test [hunk 8]
```diff
@@ -17,8 +17,9 @@ select round(5.64,1),round(5.64,2),round(5.64,-1),round(5.64,-2);
 select round(111,-10);
 select round(-5000111000111000155,-1);
 
--- @bvt:issue#3273
```
[the remark this answers is not in the document]
Comment (JackTan25) [reply test/cases/function/func_math_round.test:20]: doesn't fix deeply.

**Comment by ouyuanning** [comment]
if bugs will appear in lpad function too,  you can fixed at the same time

**Review by aressu1985 — APPROVED** [review]

**Review by JinHai-CN — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]
